In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn import svm

In [4]:
boston_data = datasets.load_boston()

In [5]:
df = pd.DataFrame(boston_data.data, columns = boston_data.feature_names)

In [8]:
X = df.values

In [9]:
y = boston_data.target

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [44]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [45]:
make_pipeline?

In [46]:
model_svm = make_pipeline(StandardScaler(), svm.SVR(kernel = 'linear', C = 0.8))

In [47]:
model_svm.fit(X_train, y_train)

Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('svr', SVR(C=0.8, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='linear', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False))])

In [48]:
model_svm.score(X_test, y_test)

0.7425845791034897

# Using Cross Validation

In [49]:
from sklearn.model_selection import cross_val_score

In [50]:
score = cross_val_score(model_svm, X, y, cv = 5)

In [51]:
score

array([0.76918567, 0.72190769, 0.56863059, 0.14337244, 0.0861383 ])

In [57]:
print(" Mean: {:.4f} and std: {:.4f}".format(score.mean(), score.std() * 2))

 Mean: 0.4578 and std: 0.5769


In [ ]:
# Using K - Fold ( Just for practice)

In [58]:
X = [ 'a', 'b', 'c', 'd']

In [59]:
y = np.arange(4)

In [65]:
KFold?

In [74]:
k_fold = KFold(n_splits = 2, shuffle = False, random_state = 0)

In [85]:
for k,v in k_fold.split(X):
    print(k, '\t', v)

[5 6 7 8 9] 	 [0 1 2 3 4]
[0 1 2 3 4] 	 [5 6 7 8 9]


# Stratified K - Fold

In [81]:
X = np.arange(10)
y = [0,0,0,0,0,1,1,1,1,1]

In [82]:
stra_k_fold = StratifiedKFold(n_splits = 3, shuffle = False )

In [83]:
for train, test in stra_k_fold.split(X,y):
    print(train, '\t', test)

[2 3 4 7 8 9] 	 [0 1 5 6]
[0 1 4 5 6 9] 	 [2 3 7 8]
[0 1 2 3 5 6 7 8] 	 [4 9]
